

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hry?useSSL=false
    username: cxj
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

    minIdle: 5
      #最大
    maxActive: 20
      #获取连接等待超时时间
    maxWait: 60000
  jdbc:
    template:
      query-timeout: 3   
      
# 配置mybatis
mybatis: 
  map-underscore-to-camel-case: true
  
  
